# ~/.config/starship.toml

[cmd_duration]
min_time = 10_000
format = "[祥$duration]($style) "

[hostname]
ssh_only = false

[custom.task_count_pending]
command = "task count rc.gc=off rc.verbose=nothing status:pending"
when = "which task"
symbol = " "
description = "Count of pending Taskwarrior tasks"

[python]
symbol = " "
